import { GoogleGenAI } from '@google/genai';
import fetch from 'node-fetch';

// Vercel Serverless Function Config
// Bypasses the EU block for Imagen 3 by running this function exclusively in the US East data center.
export const config = {
  regions: ['iad1']
};

export default async function handler(req: any, res: any) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { prompt, imageUrl } = req.body;
    let finalPrompt = prompt || 'A creative architectural design';
    const apiKey = process.env.GEMINI_API_KEY; 
    
    if (!apiKey) {
      return res.status(500).json({ error: 'Gemini API key not configured' });
    }
    
    const ai = new GoogleGenAI({ apiKey });

    // Step 1: If an imageUrl is provided, use Gemini 1.5 Flash Vision to analyze it
    // and generate an extremely detailed descriptive prompt that incorporates the layout and the user's instructions.
    if (imageUrl) {
      try {
        const imageRes = await fetch(imageUrl);
        const arrayBuffer = await imageRes.arrayBuffer();
        const base64Image = Buffer.from(arrayBuffer).toString('base64');
        
        const visionPrompt = `Analyze this reference sketch/image. The user wants to generate a final high-quality rendering based on this. Their instruction is: "${finalPrompt}". Please write an extremely detailed, vivid, midjourney-style image generation prompt that describes the exact layout, composition, shapes, and intended subjects shown in this sketch, combined with the user's styling instructions. Do not include any meta-text like "Here is the prompt", just output the raw prompt. Keep it under 1000 characters.`;
        
        const response = await ai.models.generateContent({
          model: 'gemini-1.5-flash',
          contents: [
            { role: 'user', parts: [
              { inlineData: { mimeType: 'image/png', data: base64Image } },
              { text: visionPrompt }
            ]}
          ]
        });
        
        if (response.text) {
          finalPrompt = response.text;
          console.log("Enhanced prompt from sketch:", finalPrompt);
        }
      } catch (geminiError) {
        console.error("Gemini Vision analysis failed, falling back to original prompt", geminiError);
      }
    }
    
    // Step 2: Use Imagen 3 to generate the actual image
    const response = await ai.models.generateImages({
      model: 'imagen-3.0-generate-001',
      prompt: finalPrompt,
      config: {
        numberOfImages: 1,
        outputMimeType: 'image/png'
      }
    });
    
    const base64Out = response.generatedImages?.[0]?.image?.imageBytes;
    if (!base64Out) throw new Error("No image generated by Imagen 3");

    res.status(200).json({
      imageBytes: base64Out
    });
    
  } catch (error: any) {
    console.error("Image Generation Error:", error);
    res.status(500).json({ error: 'Server error during image generation', details: error.message });
  }
}
