import { GoogleGenAI } from '@google/genai';

export const config = {
  regions: ['iad1'] // Zwinge Vercel, diese Funktion in den USA (Washington) auszuführen, um Googles EU-Geoblocking für Imagen 3 zu umgehen!
};

export default async function handler(req: any, res: any) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const apiKey = process.env.GEMINI_API_KEY; 
    
    if (!apiKey) {
      return res.status(500).json({ error: 'Gemini API key not configured' });
    }
    
    const ai = new GoogleGenAI({ apiKey });
    const { prompt, imageUrl } = req.body;
    
    let finalPrompt = prompt || 'A highly detailed architectural design, photorealistic';

    // Step 1: Use Gemini 1.5 Flash Vision to analyze the 3D block model
    if (imageUrl) {
      try {
        const imageRes = await fetch(imageUrl);
        const arrayBuffer = await imageRes.arrayBuffer();
        const base64Image = Buffer.from(arrayBuffer).toString('base64');
        
        // Ensure the prompt focuses heavily on the structural geometry!
        const visionPrompt = `Analyze this reference 3D model/sketch. The user wants to generate a high-quality architectural rendering based on this geometry. Their styling instruction is: "${finalPrompt}". Please write an extremely vivid, strictly descriptive image generation prompt. Describe the EXACT geometry, blocks, columns, and camera angle you see in the image, combined with the user's styling. DO NOT invent houses, windows, or trees if they are not in the raw geometry. Keep it under 1000 characters.`;
        
        const response = await ai.models.generateContent({
          model: 'gemini-1.5-flash',
          contents: [
            { role: 'user', parts: [
              { inlineData: { mimeType: 'image/png', data: base64Image } },
              { text: visionPrompt }
            ]}
          ]
        });
        
        if (response.text) {
          finalPrompt = response.text.trim();
          console.log("Enhanced prompt from Gemini:", finalPrompt);
        }
      } catch (geminiError) {
        console.error("Gemini Vision analysis failed:", geminiError);
      }
    }

    // Step 2: Use Imagen 3 to generate the image (running in US region to bypass blocks)
    console.log("Calling Imagen 3 with prompt:", finalPrompt);
    const response = await ai.models.generateImages({
      model: 'imagen-3.0-generate-001',
      prompt: finalPrompt,
      config: {
        numberOfImages: 1,
        outputMimeType: 'image/png',
        aspectRatio: '1:1'
      }
    });
    
    const base64ImageOut = response.generatedImages?.[0]?.image?.imageBytes;
    if (!base64ImageOut) throw new Error("No image generated by Imagen 3");

    res.status(200).json({
      imageBytes: base64ImageOut
    });
    
  } catch (error: any) {
    console.error("Imagen 3 Error:", error);
    res.status(500).json({ error: 'Server error during image generation', details: error.message });
  }
}
